[build]
  command = "hugo" # Comando para construir o site com o Hugo
  publish = "public" # Diretório de saída do Hugo, onde os arquivos gerados serão armazenados

[build.environment]
  HUGO_VERSION = "0.111.3" # Versão específica do Hugo que você deseja usar (opcional)

[context.production.environment]
  HUGO_ENV = "production" # Define o ambiente de produção para o Hugo

[context.split1]
  command = "hugo --enableGitInfo" # Comando adicional para adicionar informações do Git

[context.split1.environment]
  HUGO_ENV = "production" # Define o ambiente de produção para o Hugo no contexto split1
