name = "Doks"
license = "MIT"
licenselink = "https://github.com/social-sporte/social-sporte-api/blob/master/LICENSE"
description = "Hugo theme helping you build modern documentation websites that are secure, fast, and SEO-ready — by default."

homepage = "https://github.com/social-sporte/social-sporte-api"
demosite = "https://social-sport-api.herokuapp.com/swagger-ui.html"

tags = ["landing page", "documentation", "blog", "minimal", "modern", "customizable", "search", "dark mode", "bootstrap"]
features = ["Segurança", "fast by default", "seo-ready", "development tools", "bootstrap framework", "netlify-ready", "full text search", "page layouts", "dark mode"]

[author]
  name = "Henk Verlinde"
  homepage = "https://henkverlinde.com"
